name: finalproject # You can change this to your project's name
description: An intelligent walking companion app.
publish_to: 'none' # Remove this line if you intend to publish this package to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your SDK version is compatible

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 # A common icon set for iOS style
  flutter_tts: ^4.0.2 # For text-to-speech functionality
  geolocator: ^12.0.0 # For location services
  permission_handler: ^11.3.1 # For requesting permissions
  intl: ^0.19.0 # For date and time formatting (used in HomeScreen)
  logger: ^2.0.3 # Add this line to include the logger package
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Recommended linting rules for Flutter projects

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700